### PR TITLE
Allow overriding Promise library #265

### PR DESCRIPTION
**Pull request by Worthaboutapig**
This is done, however, there are some failing test on apparently unrelated stream issues.
There's a few changes to make tests etc easier to run under an IDE.
(Updated packages and uses pnpm)

### CODE REVIEW

**Comment by cressie176** [comment]
Thank you for the PR and sorry it has taken so long to respond. I'm closing in favour of native promise support now that support for older node versions has been dropped.

**Comment by Worthaboutapig** [comment]
> Thank you for the PR and sorry it has taken so long to respond. I'm closing in favour of native promise support now that support for older node versions has been dropped.

No problem. The approach I took handled this by using the native Promise library by default, but allowing people to pass in their own if they liked. This seems the most flexible option.

Is there an issue for the changes, are they in progress? My PR works fine in practice (though appreciate isn't necessarily suitable for merging).

**Comment by cressie176** [comment]
Hi @Worthaboutapig, I thought about whether we want people to be able to supply their own promise library and decided against it. I agree it would be more flexible, but the internals of the library should be opaque to users, and it would create potential for some difficult to diagnose bugs if we allowed people to specify their own.

https://github.com/amqp-node/amqplib/issues/627 exists and there is also a PR https://github.com/amqp-node/amqplib/pull/624

At the moment I'm picking off some smaller/simpler changes though.

**Comment by Worthaboutapig** [comment]
Ok, thanks. I made the changes because Bluebird created a bunch of problems in debugging, as it throws loads of exceptions as part of its normal startup behaviour. It was horrendous to the point of making my whole debugging experience with RabbitMQ based stuff unusable- so IMHO it's critical to being useful.
Perhaps others don't have the same debugging experience I do though.

**Pull request closed without merging**
