### PR TITLE
Drop support for especially obsolete Node versions

### PR DESCRIPTION
**Pull request by kibertoad**

### CODE REVIEW

**Comment by squaremo** [comment]
I'm on board with this, if there's no substantial dissent. Does someone mind tweeting a pointer to this PR -- see if we get some :+1: :-1:

**Comment by kibertoad** [comment]
@squaremo So what's the plan? How long do we wait for public outcry?

**Comment by kibertoad** [comment]
@squaremo Since 0.5.3 was already released, has the time came for this PR?

**Comment by 3z3qu13l** [comment]
Migration to nyc would be nice instead of outdated istanbul
https://github.com/istanbuljs/nyc

**Comment by kibertoad** [comment]
@3z3qu13l It's probably doable if nyc is locked to 11.9.0 (newer ones require Node 6+). After this PR is merged, I could provide a new one with upgrade to nyc.

**Comment by kibertoad** [comment]
@squaremo @cressie176 Any updates?..

**Comment by kibertoad** [comment]
Shall we dot it after Node V12 lands?..

**Comment by bergur** [comment]
Any news on this?

**Comment by cressie176** [comment]
All done

**Pull request closed without merging**
