### PR TITLE
[fix] attempt to fix trapping of thrown application errors by removing try catch to exit more gracefully

### LINKED ISSUE #123: Thrown errors in application are caught by underlying amqplib (using callback api)
So i was doing some tests with my [`rabbit-rr`](https://github.com/jcrugzz/rabbit-rr) library which wraps `amqplib` similar to `rabbit.js` (aside: i just needed the callback interface req/rep but THANK YOU for all your reference code). What I ran into while doing some tests (with some bad asserts in the tests at the time) was that the `amqp` library itself grabbed the thrown error from the assert and emit the error event itself.

Example can be found below where I put a `console.dir(msg)` [here](https://github.com/squaremo/amqp.node/blob/master/lib/channel.js#L236) and add a bad assert to one of my tests.

and receive the following stack from the [`assume`](https://github.com/bigpipe/assume) library I'm using.

The output of the message is followed by an output of the arguments passed to the function invoked in the `else` clause.

``` sh

{ message: 'Unknown assertation failure occured, assumed `undefined` to be truthy',
  stack: 'Unknown assertation failure occured, assumed `undefined` to be truthy 
   /Users/jcrugzz/github/jcrugzz/rabbit-rr/test/simple.test.js
    .on(\'message\', function (msg, reply) { 
      assume(msg.bar).is.ok();
      assume(msg).is.an(\'object\');
      at Assert.ok (/Users/jcrugzz/github/jcrugzz/rabbit-rr/node_modules/assume/index.js:277:15)       
      at RepSocket.<anonymous> (/Users/jcrugzz/github/jcrugzz/rabbit-rr/test/simple.test.js:108:28)      
      at RepSocket.emit (events.js:98:17)
      at RepSocket._consume (/Users/jcrugzz/github/jcrugzz/rabbit-rr/socket.js:9:8990)      
      at Channel.BaseChannel.dispatchMessage (/Users/jcrugzz/github/jcrugzz/rabbit-rr/node_modules/amqplib/lib/channel.js:459:12)
      at Channel.BaseChannel.handleDelivery (/Users/jcrugzz/github/jcrugzz/rabbit-rr/node_modules/amqplib/lib/channel.js:468:15)
      at Channel.emit (events.js:95:17)\n at /Users/jcrugzz/github/jcrugzz/rabbit-rr/node_modules/amqplib/lib/channel.js:260:10
      at Channel.content [as handleMessage] (/Users/jcrugzz/github/jcrugzz/rabbit-rr/node_modules/amqplib/lib/channel.js:313:9)
      at Channel.C.acceptMessageFrame (/Users/jcrugzz/github/jcrugzz/rabbit-rr/node_modules/amqplib/lib/channel.js:226:31)      
      at Channel.C.accept (/Users/jcrugzz/github/jcrugzz/rabbit-rr/node_modules/amqplib/lib/channel.js:381:17)     
      at Connection.mainAccept [as accept] (/Users/jcrugzz/github/jcrugzz/rabbit-rr/node_modules/amqplib/lib/connection.js:62:33)
      at Socket.go (/Users/jcrugzz/github/jcrugzz/rabbit-rr/node_modules/amqplib/lib/connection.js:465:48)
      at Socket.emit (events.js:92:17)
      at emitReadable_ (_stream_readable.js:426:10)
      at emitReadable (_stream_readable.js:422:5)
      at readableAddChunk (_stream_readable.js:165:9)
      at Socket.Readable.push (_stream_readable.js:127:10)
      at TCP.onread (net.js:528:21)\n\u001b[0m' }
{ '0': 'Internal error while processing message',
  '1': 541,
  '2': [Error: [object Object]] }
```

Typically this occurs when the function invocation is happening in a try catch but I'd love your thoughts into how this could be resolved @squaremo. Definitely interested in helping :smile:

### PR DESCRIPTION
**Pull request by jcrugzz**
@squaremo this is my attempt to fix #123 but it currently fails a few tests that I'm having difficulty reasoning about. Would love your help here if you have a minute. This seems to be reasonable as I don't see there a case where there _needs_ to be a throw or a thrown error is bound to occur but I could be wrong.

### CODE REVIEW

**Comment by squaremo** [comment]
This is one of my least favourite areas of the code -- there's just no good answer for what to do with exceptions from application code. I'll take a look as soon as I can devote a bit of time to it -- thanks!

**Comment by jcrugzz** [comment]
@squaremo yea my goal was just to avoid trapping them. The errors i found in the tests were one regarding domains with the callback API (which was calling done twice) but i don't necessarily trust domains to begin with. The other 3 were in the channel tests and they just ambiguously timed out. Thanks for the help!

**Comment by jcrugzz** [comment]
@squaremo i know this isnt on the top of your list but while attempting to implement reconnect logic around connections and channels ive seen this become more of a problem. Application code throwing errors get trapped by the state machine so that emits an error on the `channel`. Ill see if I can take another stab at it but would love some help if you have the time.

**Comment by cressie176** [comment]
Tidy up

**Pull request closed without merging**
