### PR TITLE
GitHub Actions CI

### PR DESCRIPTION
**Pull request by kibertoad**

### CODE REVIEW

**Comment by jimmywarting** [comment]
bump

**Comment by squaremo** [comment]
Any idea why this doesn't run the actions? So far as I can tell, it's not restricted to PRs only in my account.

**Comment by kibertoad** [comment]
@squaremo From my understanding, if there were no GitHub Actions before, it needs to be merged before activates.

**Comment by kibertoad** [comment]
this was already implemented

**Pull request closed without merging**
