### PR TITLE
Fix Heartbeat Intervals

### PR DESCRIPTION
**Pull request by seesemichaelj**
Hello!

I'm using this library in a production setting; and I noticed that under load I would occasionally timeout due to missing heartbeats. Looking at the logic of determining whether or not to send a heartbeat, I realized the library actually doesn't send heartbeats at t/2 intervals (as intended by the comments in `lib/heartbeat.js`) but t intervals. Under load, we could miss timeouts.

This PR changes the way the library determines whether or not we should send a heartbeat by using time with a buffer rather than a boolean flag. You'll see a test I added in https://github.com/squaremo/amqp.node/commit/fd47fbdb8485843307feb7a82c6b2d6c61c61035 that demonstrates the bug (by failing). 

Here's a potential scenario of current behavior that is failing in my production environment:
1. `sendHearbeat` is called
1. `sendBytes` is called inside `sendHeartbeat`
1. `setSinceLastCheck` set to `true` inside of `sendBytes`
1. No network traffic occurs
1. `intervalMs / 2` time elapses and `Heart.runHeartbeat` is called
1. `runHeartbeat` runs `check` which is `Connection.checkSend` in this case
1. `checkSend` returns the old value of `setSinceLastCheck` (which is `true`) and sets `setSinceLastCheck` to `false`
1. `runHeartbeat` doesn't `fail()` due to `!true` condition and therefore doesn't send a heartbeat when we'd expect it to send a heartbeat every `intervalMs / 2` given no other traffic
1. No network traffic occurs
1. `intervalMs / 2` time elapses. We're now very close to `intervalMs` which is the timeout period. Under load, the `setInterval` may be a little late and miss the timeout period
1. We get a heartbeat timeout from the server because we sent a beat a tad late

I've tested these changes in my production environment, and seem to work great

Let me know if you have any questions!

### CODE REVIEW

**Comment by cressie176** [comment]
Thanks for the PR, and sorry it has taken so long to respond. I recently investigated https://github.com/amqp-node/amqplib/issues/588#issuecomment-1126902872 and found that RabbitMQ doesn't close the connection until long after the heartbeat (or any other command) is overdue. 

Consequently I'm going to close this, but happy to reconsider if I'm wrong about RabbitMQ's behaviour.

**Comment by seesemichaelj** [comment]
While I'm no longer using this library (no longer at that company and the product was also discontinued), we did get our connections closed because of missed heartbeats. This PR was necessary for us to operate in high load scenarios. I no longer have a stake in this, but there is an implementation issue as it stands.

**Comment by cressie176** [comment]
Understood, and thanks for the update. I had the same concerns as you, but my tests clearly show it waits for almost 3x the heartbeat timeout, which is enough for one dropped heartbeat and a very slow one. It's possible I used a more modern version RabbitMQ, updated allow a longer grace period. I'll keep an eye out for any more reports.

**Comment by seesemichaelj** [comment]
Was actually about to update my comment: it's definitely possible the observed behavior was different when this PR was made. Thanks anyway for the response (and for the library; it served us well); have a good one!

**Pull request closed without merging**
